INSERT INTO Role VALUES(1, "MANAGER");
INSERT INTO Role VALUES(2, "EMPLOYEE");
INSERT INTO Role VALUES(3, "CUSTOMER");

INSERT INTO User (userId, firstName, lastName, email, password, phoneNo, addressLine, gender, roleId) VALUES
(1, "Sam", "Winchester", "sam@test.com", "$2a$10$ya.bKPIxd7Ov80gVnKk8ce9xzxdkKRfZ9gtKG4RnnWvMrEPhTHz7q", "9512346780", "Lawrence", "Male", 1),
(2, "Dean", "Winchester", "dean@test.com", "$2a$10$ya.bKPIxd7Ov80gVnKk8ce9xzxdkKRfZ9gtKG4RnnWvMrEPhTHz7q", "8521346970", "Kansas", "Male", 2),
(3, "Mary", "Winchester", "mary@test.com", "$2a$10$7z9Cb.UFXs55FPTzwK5P6u9GEhEoU6/pIuRydTjsPW6ts/zV0IAs6", "9032147856", "Florida", "Female", 2),
(4, "Eileen", "Leahy", "eileen@test.com", "$2a$10$iD4Cxj6R09qpCRSpJOz4NO.lTeyt8qKvgOmcYPnvmnJ8mGN66byJe", "7532104698", "301 Lawrence", "Female", 3),
(5, "John", "Winchester", "john@test.com", "$2a$10$1AiyRopn1oDg.U63AY9T6ORdBLt.dwxKjZM0q3YyvMA6PqDkvjNjK", "8203164597", "106 Kansas", "Male", 3)
;

INSERT INTO EmployeeDetails VALUES 
(1, 3, "885566442130", "951234567801", "AVAILABLE", '2021-10-11', 15000),
(2, 2, "884523442130", "951234567888", "PENDING", '2021-10-29', 13000)
;


INSERT INTO Cuisine VALUES 
(1, "American", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/american.jpg?raw=true", "American cuisine is the cooking style and traditional food dishes prepared in the United States. Primarily European in origin, it has been significantly influenced by indigenous Native Americans, African Americans, Asians, Pacific Islanders, and many other cultures and traditions, reflecting the diverse history of the United States"),
(2, "Chinese", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/chinese.jpg?raw=true", "Chinese food, rich and colorful, has diversified color, aromatic flavor, and excellent taste as its main features. It typically consists of a carbohydrate or starch like noodles, rice or buns, and accompanying stir fries or dishes of veggies, fish and meat. Chinese dishes are rich in umami which is described as a 'pleasant savory taste"),
(3, "French", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/french.jpg?raw=true", "French Cuisine is a heavenly amalgamation of culture, tradition, sophistication and, perhaps above all, a love for food. The French look beyond the ingredients and techniques that go into creating a rich blend of flavors making the cuisine incredibly influential, particularly in the realm of western cuisine"),
(4, "Indian", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/indian.jpg?raw=true", "Traditional cuisines native to the Indian subcontinent containing a substantial varieties of food, given the diversity in culture, ethnic groups, occupations, soil and climate. The appetizing food rich in locally spices , herbs, vegetables, and fruits serves a pallete of flavours and is hot at the same time"),
(5, "Italian", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/italian.jpg?raw=true", "A highly regionalized cuisine has a great variety of different ingredients which are commonly used, ranging from fruits, vegetables, grains, cheeses, meats and fish. Fewer but of the highest quality ingredients that can be sourced locally are used to prepare dishes which are very simple, unpretentious, but always seasonal and local"),
(6, "Japanese", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/japanese.jpg?raw=true", "Japanese cuisine includes a wide variety of products, some 1,500 different items, with rice at its center. It also emphasizes seasonal produce, and uses many fermented foods"),
(7, "Russian", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/russian.jpg?raw=true", "The main feature of Russian cuisine is considered to be an abundance and variety of products used for cooking. There are numerous dishes made of dough such as pies, cakes, rolls, blini, etc. as well as unleavened dough, including dumplings and homemade noodles"),
(8, "Spanish", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/spanish.jpg?raw=true", "Spanish cuisine consists of the cooking traditions and practices from Spain. Olive oil (of which Spain is the world's largest producer) is heavily used in Spanish cuisine"),
(9, "Thai", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/thai.jpg?raw=true", "Thai cuisine is a type of Asian cuisine that is traditionally famous for its exotic taste of spices, combined with sweet and sour"),
(10, "Turkish", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/turkish.jpg?raw=true", "Turkish cuisine is largely the heritage of Ottoman cuisine, which can be described as a fusion and refinement of Mediterranean, Balkan, Middle Eastern, Central Asian, Eastern European, Armenian, and Georgian cuisines")
;


INSERT INTO FoodItem VALUES
(1, "Banana Pancake", "With the goodness of bananas, oats and eggs, this pancake is not only delicious but also healthy! And the best part is it can be prepared in less than 10 minutes", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/american/3IngredientsBananaPancake.jpg?raw=true", 250, 12, 1),
(2, "Beer Chicken Tartar", "Making the perfect kind of batter can be a real challenge, but this recipe will put all your batter woes to rest. It's got a nice and crisp outside and juicy, tender and moist chicken on the inside", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/american/beerChickenTartar.jpg?raw=true", 400, 13, 1),
(3, "Classic American Pancakes", "Start your day with these classic American pancakes. They are easy to make and can have various toppings like maple syrup or honey or fresh berries- the choice is yours", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/american/classicAmericanPancakes.jpg?raw=true", 230, 7, 1),
(4, "Potato Chicken Stew", "A traditional American chicken curry where the chicken chunks are parboiled along with potato cubes or other veggies until tender", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/american/potatoChickenStew.jpg?raw=true", 450, 8, 1),
(5, "Potato Corn Burger", "Patties made from potatoes, corn, leeks, celery, jalapenos, feta cheese are dipped in a creamy batter, coated with breadcrumbs and deep fried", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/american/potatoCornBurger.jpg?raw=true", 300, 21, 1),
(6, "Submarines and mayo", "Sub packed with ham, cheese, salami and sauces served with homemade mayo", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/american/submarinesAndMayo.jpg?raw=true", 550, 4, 1),
(7, "Hamburgers and fries", "Succulent mutton patties pan fried to create an oozing luscious hamburger. Served with potato fries, some coleslaw, mustard and ketchup", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/american/hamburgerAndFries.jpg?raw=true", 650, 5, 1),
(8, "Jalapeno Cheese Fingers", "Cheddar cheese and jalapeno mixed in a buttery batter of cornmeal, buttermilk, salt and sugar! Baked to perfection with corn and served warm", "Succulent mutton patties pan fried to create an oozing luscious hamburger. Served with potato fries, some coleslaw, mustard and ketchup", 450, 6, 1),
(9, "Strawberry Quinoa Pancakes", "Roasted quinoa bathed in milk, dipped in orange essence and finally loaded with strawberries on top. A healthy, delicious and complete breakfast meal", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/american/strawberryQuinoaPancakes.jpg?raw=true", 300, 7, 1),
(10, "Strawberry Milkshake", "Strawberries, strawberry ice-cream and milk blend together to reach a pink perfection", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/american/strawberryMilkshake.jpg?raw=true", 250, 8, 1)
;


INSERT INTO FoodItem VALUES
(11, "Hot Pot", "Hot pot is a flavorful broth traditionally served inside a large metal pot. Raw ingredients, such as meat and vegetables, are placed into the simmering broth and thus cooked which is healthy and delicious", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/chinese/hotPot.jpeg?raw=true", 2000, 6, 2),
(12, "Kung Pao Chicken", "Kung pao chicken is a popular Chinese restaurant dish of stir-fried chicken, peanuts and vegetables. It's traditionally made with specialty ingredients, like Sichuan peppercorns, Chinese black vinegar, Chinese rice wine, and whole dried red chilies", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/chinese/kungPaoChicken.jpeg?raw=true", 1100, 13, 2),
(13, "Dim Sum", "Dim sum is a traditional Chinese meal made up of small plates of dumplings and other snack dishes and is usually accompanied by tea", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/chinese/dimSum.jpeg?raw=true", 725, 7, 2),
(14, "Dumplings", "A delicious, bite-sized food that's made of savory ingredients wrapped in dough and cooked. Get a filling made with vegetables, meat or fish — it might be a wonton, cooked in a soup, or a potsticker, steamed and then lightly fried as ordered", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/chinese/dumplings.jpeg?raw=true", 950, 4, 2),
(15, "Mo Po Tofu", "It consists of tofu set in a spicy sauce, typically a thin, oily, and bright red suspension, based on douban and douchi , along with traditional minced beef. The sauce is pleasingly oily, which ampliflies the spiciness and flavor", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/chinese/moPoTofu.jpeg?raw=true", 1300, 9, 2),
(16, "Char Siu", "As it literrally means Char siu is a fork roasted after the traditional cooking method of the long strips of seasoned boneless pork skewered with long forks and placed in a covered oven or over a fire", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/chinese/charSiu.jpeg?raw=true", 850, 4, 2),
(17, "Chowmein", "A great Chow Mein comes down to the sauce which is made with soy sauce, oyster sauce, sesame oil, sugar and cornstarch for thickening. Slippery noodles slick with the savoury Chow Mein Sauce is noodle heaven", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/chinese/chowMein.jpeg?raw=true", 875, 5, 2),
(18, "Fried Rice", "Fried rice is a dish of cooked rice that has been stir-fried in a wok or a frying pan and mixed with eggs, vegetables, seafood, or meat. A well-balanced taste of hot, pungent, tangy and mildy sweet flavors of schezwan sauce goes well as a condiment with rice", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/chinese/friedRice.jpeg?raw=true", 950, 3, 2),
(19, "Xiaolongbao", "Small Chinese steamed buns traditionally prepared in a xiaolong, a small bamboo steaming basket. The thin skin, rich flavored broth and tender pork fillings suit all tastes with the slight sweetness and umami flavors", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/chinese/xiaolongbao.jpeg?raw=true", 600, 8, 2),
(20, "Wonton Soup", "Wonton soup is a standard of Chinese cuisine and made from seasoned chicken broth with filled wontons. The soup is a clear bullion that is rich and flavorful with hints of shrimp, ginger, and toasted sesame oil", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/chinese/wontonSoup.jpeg?raw=true", 400, 7, 2)
;


INSERT INTO FoodItem VALUES
(21, "Steakfrites", "A fancy name for a steak with fried potatoes, steak frites, refers to beef steak with a side of French-fried potatoes. Served with gravy or sauce, including béarnaise, a creamy sauce made from clarified butter, herbs, and egg yolks", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/french/steakFrites.jpeg?raw=true", 450, 7, 3),
(22, "Chicken Con Fit", "The chicken cooked in it's own fat emerges meltingly tender with a rich, slightly salty but mellow flavor", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/french/chickenConfit.jpeg?raw=true", 1250, 8, 3),
(23, "French Onion Soup", "Caramelizing onions in butter and then deglazing with dry white wine French onion soup is further cooked with meat stock or veggie stock. Then finished with toasted bread or croutons with melted cheese makes it a best Veg starter", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/french/frenchOnionSoup.jpeg?raw=true", 300, 9, 3),
(24, "Salmon En Papillote", "Salmon fillets placed on a bed of vegetables, wrapped in a parchment paper pouch (en papillote) and baked in the oven. The fish is also topped with basil compound butter for extra flavor", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/french/salmonEnPapillote.jpeg?raw=true", 550, 5, 3),
(25, "Quiche Lorraine", "Quiche Lorraine is a combination of a delicious flaky Pie Crust that is filled with savory egg custard. Bacon, cheese, caramelized onions, and other fillings brings this quiche recipe from ordinary to extraordinary", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/french/quicheLorraine.jpeg?raw=true", 1050, 3, 3),
(26, "Croque Monseiur", "A croque monsieur is a hot sandwich consisting of thinly sliced baked ham and sliced creamy Emmental or Gruyère cheese on thick slices of white bread. The bread, is topped with grated cheese, and is often dipped in beaten egg before cooking as on demand", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/french/croqueMonsieur.jpeg?raw=true", 2300, 2, 3),
(27, "Hazelnut Dacquoise", "A French dessert made up of layers of baked nut meringue with a filling of dacquoise which is a meringue with a spongy texture – it's crisp and meringue-like on the outside, and soft and moist on the inside", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/french/hazelnutDacquoise.jpeg?raw=true", 1900, 7, 3),
(28, "Frangipane Tart", "Frangipane is a pastry filling made with finely ground almonds or almond meal. Well known as almond cream Frangipane has a light sweetness to it and a nutty flavor", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/french/frangipaneTart.jpg?raw=true", 1650, 5, 3),
(29, "Souffle", "Light and puffy cakes made with egg yolks, beaten egg whites, and a variety of other ingredients Soufflés are served as a savory main course or sweetened to be a delicious dessert", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/french/souffle.jpeg?raw=true", 1500, 8, 3),
(30, "Paris Brest", "Dominated by the toasted nutty flavor and aroma of praline cream the Paris-Brest is a circle of cream puffs filled with buttery hazelnut custard topped with a cap of sliced or slivered almonds, crunchy sugar, or a crumbly cookie crust as ordered", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/french/paris-Brest.jpeg?raw=true", 450, 9, 3)
;


INSERT INTO FoodItem VALUES
(31, "Chicken Tikka Masala", "The dish consists of marinated boneless chicken pieces that are traditionally cooked in a tandoor and then served in a subtly spiced tomato-cream sauce. A heated plate with onions and masala sauce quenches the hunger", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/indian/chickenTikkaMasala.jpeg?raw=true", 950, 7, 4),
(32, "Chicken Paneer Kathi Roll", "A lip smacking roll of a flaky tawa paratha stuffed with a flavourful chicken/ spicy paneer filling, mixed peppers and sweet caramelized onions. Green chutney and mix veggie salad enhances the taste", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/indian/paneerChickenKathiRoll.jpeg?raw=true", 700, 7, 4),
(33, "Southern Fried Chicken", "The dish consists of chicken pieces that have been coated with seasoned flour or batter and deep fried. The breading adds a crisp coating or crust to the exterior of the chicken while retaining juices in the meat", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/indian/southernFriedChicken.jpeg?raw=true", 1175, 5, 4),
(34, "Chana Masala", "A delicious and flavourful Indian curry made by cooking chickpeas in a spicy roasted and pureed onion tomato masala gravy. This adds an unique flavor, texture and taste to the gravy", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/indian/chanaMasala.jpeg?raw=true", 650, 9, 4),
(35, "Hyderabadi Biryani", "A spiced mix of meat/paneer and rice, cooked over an open fire in a leather pot. An aromatic additions of cardamom, saffron, cinnamon, and clove creates highly tasty and ambrosial combination", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/indian/hyderabadiBiryani(VegNon-Veg).jpeg?raw=true", 1175, 3, 4),
(36, "Palak Paneer", "Palak Paneer is one of the most popular paneer dishes. Paneer is cooked with spinach and spices in this creamy and flavorful curry.", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/indian/palakPaneer.jpeg?raw=true", 900, 5, 4),
(37, "Dal", "A special gem of a dal, infused with kasoora clay and goodness of spices! Red masoor dal with garlic and clay pieces gives this dish a beautiful earthy flavour which makes this dal recipe distinctive", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/indian/dal.jpeg?raw=true", 600, 6, 4),
(38, "Rogan Josh", "An aromatic curried red mutton dish of Kashmiri origin coloured and flavoured primarily by alkanet flower and Kashmiri chilies", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/indian/roganJosh.jpeg?raw=true", 500, 7, 4),
(39, "Malai Kofta", "A delicious dish of fried balls of potato and paneer in a rich and creamy mild gravy made with sweet onions and tomatoes. The flavour becomes even richer due to vegetables added in it", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/indian/malaiKofta.JPEG?raw=true", 800, 8, 4),
(40, "Almond Cheese Cake", "Rich almond cake with crème anglaise and vanilla pod ice cream", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/indian/almondCheeseCake.jpeg?raw=true", 650, 3, 4)
;


INSERT INTO FoodItem VALUES
(41, "Risotto Alla Melanese", "Creamy and tasty, saffron risotto is made with rice, saffron, butter, meat stock, dry white wine and Parmigiano cheese. Increased doses of Parmigiano Reggiano make it more creamy and luscious", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/italian/risottoAllaMilanese.jpeg?raw=true", 700, 11, 5),
(42, "Polenta", "The northern Italian dish freshly cooked from coarsely ground corn makes this dish soft and creamy and terrific bed for sauces. This gluten free dish is served as a hot porridge", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/italian/polenta.jpeg?raw=true", 1100, 21, 5),
(43, "Lasagna", "The crowning glories of the American-Italian dinner table with many layers of the oldest and best-known pasta, sauce, meat and melted cheese comes together to give your mouth an explosion of flavors", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/italian/lasagna.jpeg?raw=true", 650, 8, 5),
(44, "Ravioli", "Ravioli is an Italian dumpling stuffed with ricotta, meat, cheese, and vegetables. The filling is sealed between two thin layers of egg pasta dough and is served with a delicious tomato or cream-based pasta sauce", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/italian/ravioli.jpeg?raw=true", 800, 6, 5),
(45, "Osso Buco", "osso buco is a specialty of Lombard cuisine of cross-cut veal shanks braised with vegetables, white wine and broth.The marrow in the hole in the bone, a prized delicacy, is the defining feature of the dish providing the rich flavor to the sauce", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/italian/ossoBuco.jpeg?raw=true", 750, 9, 5),
(46, "Arancini", "Crispy Rounded balls of cooked rice with savory fillings of mozzarella cheese coated with bread crumbs and deep-fried are served with a punch of black pepper", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/italian/arnacini.JPEG?raw=true", 450, 12, 5),
(47, "Ribolitta", "A specialty of the Tuscany region of Italy which is a type of thick soup. Pancetta, zucchini and cannellinin added to the minestrone soup is ladled over slices of crusty bread toasted, rubbed with garlic and splashed with olive oil and broiled", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/italian/ribollita.jpeg?raw=true", 1150, 15, 5),
(48, "Spaghetti Alla Carbonara", "Spaghetti carbonara is an Italian main course consisting of spaghetti with bacon and a creamy sauce made from eggs, Pecorino or Parmesan and black pepper", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/italian/spaghettiAllaCarbonara.jpeg?raw=true", 900, 4, 5),
(49, "Nepolitan Pizza", "Baked in a wood fired pizza oven Neapolitan pizza having a very thin crust at the base, with dough that puffs up around the sides and provides for a very airy crust. On an addition tomatoes from volcanic plains gives a sun-ripe taste", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/italian/neapolitanPizza.jpg?raw=true", 975, 9, 5),
(50, "Caprese Salad", "The salad consists of slices of mozzarella and tomatoes, basil, and olive oil or Italian dressing. Served with Caprese sauce this classic Italian dish that has gained popularity all over the world", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/italian/capreseSalad.jpeg?raw=true", 750, 9, 5)
;


INSERT INTO FoodItem VALUES
(51, "Sushi", "Sushi, a staple rice dish of Japanese cuisine, consisting of cooked rice flavoured with vinegar and a variety of vegetable, egg, or raw seafood garnishes and served cold", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/japanese/sushi.jpeg?raw=true", 1300, 8, 6),
(52, "Ramen", "Ramen is a Japanese noodle soup, with a combination of a rich flavoured broth and a selection of meats or vegetables, often topped with a boiled egg. Kansui added in the RAmen for sure provides it a unique flavor and eating experience making it addictisve", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/japanese/ramen.jpeg?raw=true", 600, 7, 6),
(53, "Tempura", "Tempura is a popular Japanese dish in which a perfect blend of seafood and vegetables is lightly battered and deep fried to create a light, crispy coating. Despite being fried food, it does not taste heavy or oily at all", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/japanese/tempura.jpeg?raw=true", 925, 8, 6),
(54, "Kare Raisu", "Japanese curry, also known as kare raisu (curry rice), is a dish of vegetables and beef—in a thick curry sauce served with rice. The broth is more complex, with a distinctly Japanese flavor. Grated apple adds a subtly sweet tone to the dish", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/japanese/kareRaisu.jpeg?raw=true", 775, 5, 6),
(55, "Okonomiyaki", "Okonomiyaki is a popular pan-fried dish that consists of batter and cabbage. Selected toppings and ingredients of meat and seafood to wasabi and cheese are added. The Hiroshima-style is used for cooking the batter making it more crispy and tasty", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/japanese/okonomiyaki.jpeg?raw=true", 800, 6, 6),
(56, "Shabu Shabu", "Shabu shabu is a popular hot pot dish from Japan consisting of thinly sliced meat and bite-sized vegetables cooked in steaming hot broth. Paper-thin slices of beef and pork lighter than regular meat will be offered", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/japanese/shabuShabu.jpeg?raw=true", 2500, 9, 6),
(57, "Onigiri", "Prepared from white rice formed into triangular or cylindrical shapes and often wrapped in nori grilled onigiri has a very tasty crispy texture and apetizing crunch when served hot", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/japanese/onigiri.jpeg?raw=true", 650, 4, 6),
(58, "Udon", "Quick cashew cream is the foundation for the creamy udon noodles and a perfect drizzle over roasted carrots and chickpeas. This is the one of the favorite comfort foods of Japan", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/japanese/udon.jpeg?raw=true", 700, 6, 6),
(59, "Katsudon", "Katsudon is a popular dish featuring a large donburi (bowl of rice) topped with katsu that has been simmered with onions and egg in a sweet and savory broth. The katsudon served has katsu that manages to stay crisp even after absorbing all the delicious simmering broth making the dish best one", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/japanese/katsudon.jpeg?raw=true", 625, 9, 6),
(60, "Green Tea and Flavoured Sweets", "Steamed green teas which tastes bittersweet authenticating the premium quality of tea leaves. Served in 3 flavors viz", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/japanese/greenTeaAndFlavoredSweets.jpeg?raw=true", 300, 7, 6)
;


INSERT INTO FoodItem VALUES 
(61, "Borscht", "Borscht is full of meat and sautéed vegetables, including cabbage, carrots, onions, and potatoes", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/russian/borscht.jpg?raw=true", 550, 8, 7),
(62, "Shchi", "Shchi is a typical cabbage soup made from fresh cabbage.shchi contains potatoes, carrots, onions, and possibly some type of meat such as chicken", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/russian/shchi.jpg?raw=true", 450, 7, 7),
(63, "Solyanka", "Solyanka is made with various types of meat, including sausage, bacon, ham, and beef, as well as vegetables such as cabbage, carrots, onions, and potatoes", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/russian/solyanka.jpg?raw=true", 590, 9, 7),
(64, "Ukha", "Ukha is a traditional fish soup, consisting, in addition to the obvious primary ingredient, spices, potatoes, carrots, onions, and, less commonly, other veggies", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/russian/ukha.jpg?raw=true", 650, 5, 7),
(65, "Pirozhki", "These little baked or fried puff pastries are packed full of potatoes, meat, cabbage, or cheese", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/russian/pirozhki.jpg?raw=true", 300, 6, 7),
(66, "Pelmeni", "Pelmeni are made of minced meat or fish, mixed with herbs and chopped onion or garlic, wrapped in thin dough, and are either fried or boiled", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/russian/pelmeni.jpg?raw=true", 570, 4, 7),
(67, "Blini", "Blini is a wheat pancake rolled with a variety of fillings: jam, cheese, sour cream, caviar, onions, or even chocolate syrup", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/russian/blini.jpg?raw=true", 350, 3, 7),
(68, "Shashlyk", "Russian kebabs are called shashlyk or shashlik. Like any kebab, they consist of cubed meat and veggies grilled on skewers", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/russian/shashlyk.jpg?raw=true", 600, 8, 7),
(69, "Beef Strongnaoff", "Beef stroganoff consists of strips of beef in a creamy sauce with mushrooms or tomatoes, often served with rice, noodles, or potatoes", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/russian/beefStroganoff.jpg?raw=true", 660, 7, 7),
(70, "Ikra", "Briny and sharp, it is often served on dark, crusty bread or with blini, which are like pancakes or crepes", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/russian/ikra.jpg?raw=true", 390, 9, 7)
;


INSERT INTO FoodItem VALUES
(71, "Paella", "Paella is a classic Spanish rice dish made with rice, saffron, vegetables, chicken, and seafood cooked and served in one pan", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/spanish/paella.jpg?raw=true", 650, 8, 8),
(72, "Tortilla", "A classic Spanish omelette filled with pan-fried potatoes and onion. It makes a delicious light vegetarian meal or an easy tapas dish", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/spanish/tortilla.jpg?raw=true", 450, 9, 8),
(73, "Churros", "A churro is a type of fried dough from Spanish and Portuguese cuisine.We don't often feel like breaking out all of our oil to fry things", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/spanish/churros.jpg?raw=true", 400, 7, 8),
(74, "Gazpacho", "Gazpacho is the quintessential summer soup because all of the fresh ingredients are deliciously in season this time of year, and there’s no need to heat up your stove or oven", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/spanish/gazpacho.jpg?raw=true", 470, 6, 8),
(75, "Callos Madrilena", "Callos Madrilena is a stewed tripe dish, cooked slowly for hours over low heat, that includes pig snout and trotters, black pudding, sausage, ham, and soup vegetables like carrots and onions", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/spanish/callosMadrilena.jpg?raw=true", 600, 9, 8),
(76, "Angulas", "The way we make spicy garlic angulas it is pretty simple. Garlic, fresh chili pepper and little olive oil! Everything goes in a pan altogether with angulas", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/spanish/angulas.jpg?raw=true", 630, 3, 8),
(77, "Migas", "eggs scrambled with crispy tortillas, garlic, jalapeno, and melted cheese served with black beans and avocado. Quick, easy, and SO DELICIOUS. Breakfast, lunch, dinner, or brunch", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/spanish/migas.jpg?raw=true", 590, 6, 8),
(78, "Murcian Style Clams", "The Murcian clams are prepared in a wonderful sauce made of white wine, sweet paprika, garlic and onion and have a slight bite from the red pepper flakes", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/spanish/murcianStyleClams.jpg?raw=true", 660, 7, 8),
(79, "Calamari Plancha", "This Spanish-inspired calamari dish is deliciously spicy side, infused with the flavors of fresh garlic and parsley. Don't be shy with the seasonings—this dish is meant to be bold", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/spanish/calamariPlancha.jpg?raw=true", 390, 6, 8),
(80, "Sangria", "Fast forward to current day and you’ll still find the red wine, orange juice, brandy, and sliced fruit mix being served in Spain. wine was often added to the water with the hopes that the alcohol would kill any bacteria in the drink", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/spanish/sangria.jpg?raw=true", 580, 9, 8)
;


INSERT INTO FoodItem VALUES
(81, "Spicy Shrimp Soup", "A combination of chicken and seafood stock simmered with jalapeno, a truckload of garlic, dried herbs and lime juice literally warms you from the inside out", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/thai/spicyShrimpSoup.jpg?raw=true", 450, 7, 9),
(82, "Thai Chicken Coconut Soup", "This classic chicken and coconut soup gets its rich and dynamic flavor from quintessential Thai ingredients", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/thai/thaiChickenCoconutSoup.jpg?raw=true", 470, 8, 9),
(83, "Noodle Soup", "A variation of the classic Thai noodle soup. This soup is made with the goodness of chicken, peanuts, broccoli, rice vermicelli, coconut and fried garlic", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/thai/noodleSoup.jpg?raw=true", 500, 6, 9),
(84, "Thai Fried Noodles", "This stir-fried noodle recipe boasts a flavorful stir-fry sauce along with carrots, mushrooms, broccoli, red pepper, and bean sprouts", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/thai/thaiFriedNoodles.jpg?raw=true", 400, 9, 9),
(85, "Thai Fried Rice", "Thai Fried Rice popularly called ‘Khao Pad’ in the local language is a stir-fried rice recipe with lots of Thai basil, bird’s eye chilies, veggies, and sauces", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/thai/thaiFriedRice.jpg?raw=true", 430, 5, 9),
(86, "Red Curry Chicken", "This is a quick and easy curry stir-fry made with chicken, zucchini, red bell pepper and carrot. Coconut milk and curry paste make an irresistible sauce", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/thai/redCurryChicken.jpg?raw=true", 550, 3, 9),
(87, "Green Curry With Chicken", "This easy green curry is made with chicken, coconut milk, fresh herbs, and lime. You'll have a stunning dish to admire, smell, and taste", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/thai/greenCurryChicken.jpg?raw=true", 570, 8, 9),
(88, "Thai Yellow Curry", "this is a spicy vegetarian as well as vegan Thai curry made with coconut milk and Thai herbs-spices", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/thai/thaiYellowCurry.jpg?raw=true", 570, 9, 9),
(89, "Pork And Holy Basil Fry", "pork & holy basil-stir-fry features a key ingredient: holy basil! With jasmine rice, it’s perfection. And it only takes minutes to make", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/thai/porkAndHolyBasilFry.jpg?raw=true", 490, 6, 9),
(90, "Green Papaya Salad", "The classic northern Thai salad called som tam is often eaten with sticky rice and such ingredients as very small Thai eggplants, little tomatoes, crushed peanuts, dried shrimp, long beans, crispy pork and even salted crabs", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/thai/greenPapayaSalad.jpg?raw=true", 390, 7, 9)
;


INSERT INTO FoodItem VALUES
(91, "Iskender Kebab", "Iskender kebab is prepared from thinly and carefully cut grilled lamb topped with hot tomato sauce over pieces of pita bread and generously slathered with melted special sheep's milk butter and yogurt", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/turkish/iskenderKebab.jpg?raw=true", 690, 5, 10),
(92, "Manti", "Manti is an extraordinary dish from Turkey with tiny lamb-stuffed dumplings topped with three sauces, caramelized tomato sauce, brown butter sauce, and garlicky yogurt sauce", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/turkish/manti.jpg?raw=true", 650, 6, 10),
(93, "Meze", "Meze consist of white cheese,sliced ripe melon,hot pepper paste often with walnuts,thick strained yogurt with herbs, cold eggplant salad,fried calamari,fried mussels,yogurt with cucumber and garlic,rice-stuffed vine leaves", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/turkish/meze.jpg?raw=true", 590, 4, 10),
(94, "Baklava", "Baklava is a layered pastry dessert made of filo pastry, filled with chopped nuts, and sweetened with syrup or honey. It was one of the most popular sweet pastries of Ottoman cuisine", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/turkish/baklava.jpg?raw=true", 350, 8, 10),
(95, "Turkish Apple Tea", "Turkish apple tea is a drink made by steeping dried apple pieces or dissolving apple flavored granules or powder in boiling water. It's served in small, 100 ml tulip shaped glasses without handles", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/turkish/turkishAppleTea.jpg?raw=true", 300, 9, 10),
(96, "Gozleme", "Gozleme is a savory Turkish stuffed turnover.it's traditionally made without yeast; only requires 4 ingredients: flour, olive oil, salt and water.Gozleme pastry is possible the easiest flatbread in the world", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/turkish/gozleme.jpg?raw=true", 350, 6, 10),
(97, "Kumpir", "Kumpir is basically a baked potato with cheese, Turkish version of the UK's jacket potatoes.The base for a Turkish baked potato recipe always remains the same; large potatoes, butter, cheese and a bit of seasoning", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/turkish/kumpir.jpg?raw=true", 400, 7, 10),
(98, "Karniyarik", "Karniyarik is a classic Turkish stuffed eggplant recipe. Delicious eggplants are stuffed with a tasty ground beef, pepper and tomatoes filling and are baked to perfection", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/turkish/karniyarik.jpg?raw=true", 650, 3, 10),
(99, "Simit", "Simit is a sesame crusted, circular bread from Turkey,typically encrusted with sesame seeds or, less commonly, poppy, flax or sunflower seeds", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/turkish/simit.jpg?raw=true", 400, 4, 10),
(100, "Etli Ekmek", "Etli ekmek is a delicious Turkish pizza-like dish.The name of the dish means bread with meat. It consists of a thin, crispy flatbread made with flour, sugar, salt, yeast, and oil, which is then topped with ground beef and finely chopped onions, tomatoes, and peppers", "https://github.com/geronimo-98/Emerald-Oasis-ImageDB/blob/main/Cuisines/turkish/etliEkmek.jpg?raw=true", 600, 6, 10)
;


